name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.13.2"

      - name: Build project
        run:  yarn install && yarn build
        
      - name: upload files to server
        uses: vacare/anofuss-upload@v1
        with:
          host: ${{ secrets.Host }}
          username: ${{ secrets.UserName }}
          key: ${{ secrets.Password }}
          known_hosts: ${{ secrets.Known_Hosts }}
          source: ./build/
          target: /www/wwwroot/blog.narojay.site

