name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.13.2"

      - name: set taobao mirror source
        run: npm config set registry https://registry.npm.taobao.org && npm config set disturl https://npm.taobao.org/dist && npm config rm proxy && 
             npm config rm https-proxy 

      - name: Build project
        run: yarn install && yarn build

